### ISSUE TITLE
Any pretrained model?

### ISSUE THREAD

**Issue by duchengyao** [baldFemale/beautyGAN-tf-Implement#1]
Thanks for the great project

I am running main.py with modified `./all/images/non-makeup`, `./all/images/makeup`, `./preTrainedModel` and `to_train=False` , `to_test = True`

But in this line https://github.com/baldFemale/beautyGAN-tf-Implement/blob/master/main.py#L450 ,need some checkpoint file.

Could you please provide some pretrained model for test?

Thanks so much

**Comment by HOU-Zhe0314** [comment]
Bro, how did you solve this problem in the end? Could you give me some suggestions? Thank you very much!

**Comment by duchengyao** [comment]
not solved yet...

**Comment by HOU-Zhe0314** [comment]
Bro, if you are still working on this project, we can communicate by weChat. I have acquired the pretrained models, but there are some other problems in the code, maybe we can discuss about it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baldFemale/beautyGAN-tf-Implement"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 中午11:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baldFemale/beautyGAN-tf-Implement] Any pretrained model? (#1)





 
not solved yet...
